##### The cell below is for you to keep track of the libraries used and install those libraries quickly
##### Ensure that the proper library names are used and the syntax of `%pip install PACKAGE_NAME` is followed

In [2]:

!pip install google
# add commented pip installation lines for packages used as shown above for ease of testing
# the line should be of the format %pip install PACKAGE_NAME

Requirement already satisfied: google in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (3.0.0)
Requirement already satisfied: beautifulsoup4 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from google) (4.12.3)
Requirement already satisfied: soupsieve>1.2 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from beautifulsoup4->google) (2.5)

[notice] A new release of pip is available: 23.0.1 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip

## **DO NOT CHANGE** the filepath variable
##### Instead, create a folder named 'data' in your current working directory and 
##### have the .csv file inside that. A relative path *must* be used when loading data into pandas

In [3]:
# Can have as many cells as you want for code
import pandas as pd
import numpy as np
from google.colab import drive
drive.mount('/content/drive')


df2 = pd.read_csv('https://drive.google.com/file/d/1bAFbHJYDGFbsEDoMFACd4sNxLTfOyJ7T/view?usp=drive_link')
# the initialised filepath MUST be a relative path to a folder named data that contains the parquet file

ModuleNotFoundError: No module named 'google'

### **ALL** Code for machine learning and dataset analysis should be entered below. 
##### Ensure that your code is clear and readable.
##### Comments and Markdown notes are advised to direct attention to pieces of code you deem useful.

In [3]:
df2 = pd.read_csv(filepath)
print(df2.info())

FileNotFoundError: [Errno 2] No such file or directory: './data/catA_train.csv'

In [ ]:
# find the number of rows and columns in our dataset
print(df2.shape)

# find the names of columns in our dataset
print(df2.columns)

(29182, 28)
Index(['LATITUDE', 'LONGITUDE', 'AccountID', 'Company', 'SIC Code', 'Industry',
       '8-Digit SIC Code', '8-Digit SIC Description', 'Year Found',
       'Entity Type', 'Parent Company', 'Parent Country', 'Ownership Type',
       'Company Description', 'Square Footage',
       'Company Status (Active/Inactive)', 'Employees (Single Site)',
       'Employees (Domestic Ultimate Total)',
       'Employees (Global Ultimate Total)',
       'Sales (Domestic Ultimate Total USD)',
       'Sales (Global Ultimate Total USD)', 'Import/Export Status',
       'Fiscal Year End', 'Global Ultimate Company', 'Global Ultimate Country',
       'Domestic Ultimate Company', 'Is Domestic Ultimate',
       'Is Global Ultimate'],
      dtype='object')

In [ ]:
df2.isna().sum()

LATITUDE                                 120
LONGITUDE                                120
AccountID                                  0
Company                                    0
SIC Code                                   0
Industry                                   0
8-Digit SIC Code                           0
8-Digit SIC Description                    0
Year Found                               434
Entity Type                                0
Parent Company                           514
Parent Country                           520
Ownership Type                             0
Company Description                        0
Square Footage                         29182
Company Status (Active/Inactive)           0
Employees (Single Site)                12403
Employees (Domestic Ultimate Total)       79
Employees (Global Ultimate Total)       2774
Sales (Domestic Ultimate Total USD)        0
Sales (Global Ultimate Total USD)          0
Import/Export Status                   22569
Fiscal Year End                        22445
Global Ultimate Company                  514
Global Ultimate Country                  523
Domestic Ultimate Company               1035
Is Domestic Ultimate                       0
Is Global Ultimate                         0
dtype: int64

In [ ]:
df2.describe()

,LATITUDE,LONGITUDE,SIC Code,8-Digit SIC Code,Year Found,Square Footage,Employees (Single Site),Employees (Domestic Ultimate Total),Employees (Global Ultimate Total),Sales (Domestic Ultimate Total USD),Sales (Global Ultimate Total USD),Is Domestic Ultimate,Is Global Ultimate
count,29062.000000,29062.000000,29182.000000,2.918200e+04,28748.000000,0.0,16779.000000,29103.000000,2.640800e+04,2.918200e+04,2.918200e+04,29182.000000,29182.000000
mean,1.320677,103.843324,6169.271160,6.169092e+07,2004.505913,NaN,36.856189,139.764182,6.994665e+03,7.520992e+08,3.931771e+09,0.500069,0.257248
std,0.043740,0.053757,1705.845535,1.705778e+07,13.464238,NaN,173.334420,1118.939249,4.539462e+04,1.019636e+10,2.184589e+10,0.500009,0.437125
min,1.238792,103.611319,132.000000,1.320000e+06,1819.000000,NaN,1.000000,1.000000,1.000000e+00,-1.502631e+08,1.000000e+00,0.000000,0.000000
25%,1.284665,103.831874,5084.000000,5.084000e+07,1997.000000,NaN,10.000000,4.000000,4.000000e+00,1.026308e+06,1.026308e+06,0.000000,0.000000
50%,1.309701,103.848989,6719.000000,6.719000e+07,2008.000000,NaN,16.000000,16.000000,1.500000e+01,2.606644e+06,3.259582e+06,1.000000,0.000000
75%,1.337889,103.865922,7311.000000,7.311000e+07,2014.000000,NaN,29.000000,60.000000,1.000000e+02,2.176969e+07,1.482258e+08,1.000000,1.000000
max,1.469800,104.003218,9721.000000,9.721990e+07,2023.000000,NaN,12000.000000,80000.000000,2.190000e+06,3.184764e+11,5.140000e+11,1.000000,1.000000

In [ ]:
df2.head()

,LATITUDE,LONGITUDE,AccountID,Company,SIC Code,Industry,8-Digit SIC Code,8-Digit SIC Description,Year Found,Entity Type,...,Employees (Global Ultimate Total),Sales (Domestic Ultimate Total USD),Sales (Global Ultimate Total USD),Import/Export Status,Fiscal Year End,Global Ultimate Company,Global Ultimate Country,Domestic Ultimate Company,Is Domestic Ultimate,Is Global Ultimate
0,1.285495,103.843852,LAKB2BID4559214,FRANK CONSULTING SERVICES PRIVATE LIMITED,7361.0,Employment Agencies,73610000.0,Employment agencies,2020.0,Subsidiary,...,NaN,2.209224e+06,4.637871e+06,NaN,NaN,FINDERS HOLDCO LIMITED,United Kingdom,FRANK RECRUITMENT GROUP PRIVATE LTD.,0.0,0.0
1,1.291294,103.827476,LAKB2BID7610849,NEW DESERT ORCHID SHIPPING PTE. LTD.,4449.0,"Water Transportation of Freight, Not Elsewhere...",44490000.0,Water transportation of freight,2015.0,Subsidiary,...,100.0,7.093536e+09,7.093536e+09,NaN,NaN,PETREDEC PTE. LIMITED,Singapore,NaN,0.0,0.0
2,1.300144,103.857517,LAKB2BID5461679,2MBAO BIOCELLBANK PTE. LTD.,6719.0,"Offices of Holding Companies, Not Elsewhere Cl...",67190000.0,"Holding companies, nec",1993.0,Subsidiary,...,4.0,1.026308e+06,1.026308e+06,NaN,NaN,MADISON LIGHTERS AND WATCHES CO LTD,Hong Kong SAR,2MBAO BIOCELLBANK PTE. LTD.,1.0,0.0
3,1.300785,103.791263,LAKB2BID5088529,NEWBLOOM PTE. LTD.,6719.0,"Offices of Holding Companies, Not Elsewhere Cl...",67190000.0,"Holding companies, nec",2006.0,Subsidiary,...,100.0,7.339898e+10,7.339898e+10,NaN,NaN,WILMAR INTERNATIONAL LIMITED,Singapore,WILMAR INTERNATIONAL LIMITED,0.0,0.0
4,1.298759,103.859430,LAKB2BID1268831,ASIA GREEN CAPITAL PTE. LTD.,6719.0,"Offices of Holding Companies, Not Elsewhere Cl...",67190000.0,"Holding companies, nec",2006.0,Parent,...,4.0,4.322130e+05,4.322130e+05,Exports,NaN,ASIA GREEN CAPITAL PTE. LTD.,Singapore,ASIA GREEN CAPITAL PTE. LTD.,1.0,1.0

##### Removing lat and long

In [ ]:
# removes rows without either lat or long coordinates
df2 = df2.dropna(subset=["LATITUDE", "LONGITUDE"])

##### Handling categorical variables

In [ ]:
# Remove rows where the Company Status is 'Inactive'
df2 = df2[df2['Company Status (Active/Inactive)'] == 'Active']

# to ensure important info isnt being lost
df2['Import/Export Status_Missing'] = df2['Import/Export Status'].isna()

df3 = df2.dropna(subset=["Employees (Single Site)", "Employees (Domestic Ultimate Total)", "Employees (Global Ultimate Total)",
                                       "Year Found"])

df3 = pd.get_dummies(df2, columns=['Entity Type'], prefix='Entity_Type')
df3 = pd.get_dummies(df2, columns=['Ownership Type'], prefix='Ownership_Type')
df3 = pd.get_dummies(df2, columns=['Import/Export Status'], prefix='Import_Export_Status')
df3 = df2.drop(columns=[col for col in ["Company Status (Active/Inactive)", "Entity Type", 'Import/Export Status', 'Ownership Type'] if col in df2.columns], errors='ignore') # are all Active

In [ ]:
from sklearn.preprocessing import LabelEncoder

# Use label encoding for 'SIC Code'
label_encoder = LabelEncoder()
df3['SIC Code'] = label_encoder.fit_transform(df3['SIC Code'])

df3["SIC Code"].unique()

array([487, 277, 459, 308, 351, 531,  56, 497, 135, 115, 461, 502, 458,
       411, 508, 293, 477, 247, 565,  22, 556, 265, 337, 569, 369, 344,
       564, 568, 465, 456, 347,  62,   8, 279, 296, 412, 142, 489, 327,
       474, 301, 332, 581, 350, 237, 282, 312, 397, 364, 340, 528, 455,
       262, 535, 339, 147, 183, 486, 320, 451, 273, 249, 430,  88, 492,
       419, 511, 290,  41, 470, 379, 551, 462, 560, 348, 436, 281, 466,
       371, 117, 181, 514, 450, 318, 311, 317, 513, 221, 373, 144, 358,
       566, 111, 302, 484, 330, 316, 190, 577, 534, 377, 325, 324, 546,
       114, 274, 206, 433, 372, 100, 323, 375, 328, 443, 464, 491, 256,
        89, 389, 403, 223,  17,  26,  25, 501, 460, 210, 452, 494, 547,
        30, 333, 329, 170, 368, 424, 255, 215, 341, 526, 426, 516, 542,
       198, 555, 227, 250, 131, 434, 561,  11,  55, 409, 285, 267,  85,
       481, 527, 225, 342, 415,  43, 195, 251, 498, 208,  93, 545, 186,
       136,  18,  29, 463, 567, 152, 483,  82, 298,  42, 374, 322, 122,
       558, 365, 537, 173, 346, 454, 390, 248, 162, 543, 360,  37, 194,
       126,  32, 402,  38, 384, 391, 571, 448, 233, 236,  48, 243, 244,
       439, 445, 315, 139,  76, 118,  24, 307, 246, 150, 488, 123, 387,
       357, 102, 400, 417, 154,  16, 254, 203, 352, 500, 363,  57, 286,
       297, 319, 518, 240, 541, 490, 187, 447, 180, 134, 166, 334, 283,
        45, 253, 160,  96,  33, 431, 202,  66,  79, 499, 533, 201, 213,
       383, 241,  81, 507, 222, 106, 407, 143,  51,  15, 422, 438, 495,
       473, 562, 572, 193, 263,  70, 212, 309, 288, 413, 299,  69, 218,
       559,  95, 310, 165,  73, 232, 471, 453,  75, 105, 145, 245, 278,
       356, 416,   7, 171, 331, 343, 529, 313, 108, 112,  60, 294, 392,
       101, 132, 521, 355,  28, 540, 231, 550, 536, 276, 444, 345,  50,
       178, 532, 423,  99, 305, 235,  63, 418, 362, 176, 432, 192, 119,
        47, 367, 156, 200, 314, 563, 381,  44, 548,  94,  20, 496, 300,
       207, 189, 146, 442, 366, 515,  34,  27, 291, 271, 239, 257, 209,
       169, 429, 553, 191, 557, 485, 220, 155, 184, 287, 493, 197, 321,
       523, 268, 469, 336, 349, 421,  90, 116, 509, 512, 242, 440, 338,
       420, 427, 476, 382, 138, 120, 503,  46, 353, 524, 457,  92, 185,
       129, 361, 468, 359, 182, 326, 449, 121, 107, 159, 113,  36, 504,
        84, 378, 525, 335, 395, 229, 406, 163, 479, 161, 228, 520, 399,
        58,  21, 441, 127,   9,  59, 205, 103,  68,  65, 405, 280, 354,
        77, 284, 467, 104,  86, 258,  23, 435,  31, 219,  40, 196, 394,
       157, 264, 266, 437,   3,  97, 158, 446,   2, 393,  12, 478, 133,
       549, 576, 385, 570, 272,  78,  72, 544, 530, 580, 475, 408, 175,
       574, 167,   5,   1, 292,  98, 554, 506,  39, 128, 414, 480, 510,
         6, 552, 270, 482, 124,  49, 376, 125, 188, 575,  35, 179,  87,
       404, 172, 538,  19,  74, 505,  53, 148,  13,  61, 153, 110, 177,
       217, 519, 295, 164,  14, 238,  64, 130, 428, 226,  54,  67, 306,
       204, 214, 224, 304,  91, 579, 234,   4, 259, 141,  83, 211, 140,
       380, 398, 401,  10, 230, 151, 109, 425,  71,   0, 289, 396,  52,
       522, 410, 174, 269, 199, 517, 573, 216, 388, 386, 578, 303, 539,
       370,  80, 149, 472, 261, 168, 275, 260, 252, 137], dtype=int64)

#### correlation mat

In [ ]:
# use of a correlation matrix to observe how variables in our dataset may be affected by others
numerical_df = df3.select_dtypes(include=['float64', 'int64'])

# Create a correlation matrix
correlation_matrix = numerical_df.corr()

# Assuming correlation_matrix is your correlation matrix
correlation_df = pd.DataFrame(correlation_matrix)

# Print or use the correlation DataFrame as needed
correlation_df

,LATITUDE,LONGITUDE,SIC Code,8-Digit SIC Code,Year Found,Square Footage,Employees (Single Site),Employees (Domestic Ultimate Total),Employees (Global Ultimate Total),Sales (Domestic Ultimate Total USD),Sales (Global Ultimate Total USD),Is Domestic Ultimate,Is Global Ultimate
LATITUDE,1.000000,-0.048014,-0.092148,-0.086741,-0.023920,NaN,0.001218,0.004256,-0.010028,0.004602,-0.010685,-0.004247,-0.039308
LONGITUDE,-0.048014,1.000000,0.026159,0.027591,-0.008341,NaN,-0.006147,0.013906,0.003871,-0.006884,0.008687,0.001314,0.009406
SIC Code,-0.092148,0.026159,1.000000,0.984491,0.196599,NaN,-0.058599,-0.022377,0.001511,-0.007803,-0.012523,0.014756,0.091349
8-Digit SIC Code,-0.086741,0.027591,0.984491,1.000000,0.195899,NaN,-0.051843,-0.022186,0.001599,-0.011617,-0.014653,0.016634,0.087467
Year Found,-0.023920,-0.008341,0.196599,0.195899,1.000000,NaN,-0.060604,-0.046587,-0.026246,0.014576,-0.022241,0.076406,0.112065
Square Footage,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Employees (Single Site),0.001218,-0.006147,-0.058599,-0.051843,-0.060604,NaN,1.000000,0.138964,0.008485,0.003552,0.001486,-0.016532,0.004826
Employees (Domestic Ultimate Total),0.004256,0.013906,-0.022377,-0.022186,-0.046587,NaN,0.138964,1.000000,0.020450,0.016899,0.024313,-0.060773,-0.044315
Employees (Global Ultimate Total),-0.010028,0.003871,0.001511,0.001599,-0.026246,NaN,0.008485,0.020450,1.000000,-0.003975,0.664014,0.076335,-0.087309
Sales (Domestic Ultimate Total USD),0.004602,-0.006884,-0.007803,-0.011617,0.014576,NaN,0.003552,0.016899,-0.003975,1.000000,0.098417,-0.054627,-0.039397
Sales (Global Ultimate Total USD),-0.010685,0.008687,-0.012523,-0.014653,-0.022241,NaN,0.001486,0.024313,0.664014,0.098417,1.000000,0.038098,-0.096169
Is Domestic Ultimate,-0.004247,0.001314,0.014756,0.016634,0.076406,NaN,-0.016532,-0.060773,0.076335,-0.054627,0.038098,1.000000,0.588917
Is Global Ultimate,-0.039308,0.009406,0.091349,0.087467,0.112065,NaN,0.004826,-0.044315,-0.087309,-0.039397,-0.096169,0.588917,1.000000

##### feature selection

In [ ]:
# Specify columns to drop
columns_to_drop = ["error", "Fiscal Year End", "Sales (Global Ultimate Total USD)", "Global Ultimate Company", "Domestic Ultimate Company", "Web Address",
                   "Sales (Global Ultimate Total USD)", "Square Footage", "Company Description", "PostCode", "8-Digit SIC Code", "8-Digit SIC Description", "AccountID",
                   "Parent Company", "City", "Country", "Address", "Address1", "Industry", "Region", "Parent Country", "Global Ultimate Country", "Company"]

# Drop columns if they exist in the DataFrame
df4 = df3.drop(columns=[col for col in columns_to_drop if col in df3.columns], errors='ignore')

In [ ]:
df4 = df4.dropna(subset=["Employees (Single Site)", "Employees (Domestic Ultimate Total)", "Employees (Global Ultimate Total)",
                                       "Year Found"])

In [ ]:
# Convert 'Is Domestic Ultimate' to True/False
df4['Is Domestic Ultimate'] = df4['Is Domestic Ultimate'] == 1
df4['Is Global Ultimate'] = df4['Is Global Ultimate'] == 1

In [ ]:
# use of a correlation matrix to observe how variables in our dataset may be affected by others
numerical_df = df4.select_dtypes(include=['float64', 'int64'])

# Create a correlation matrix
correlation_matrix = numerical_df.corr()

# Assuming correlation_matrix is your correlation matrix
correlation_df = pd.DataFrame(correlation_matrix)

# Print or use the correlation DataFrame as needed
df4.head()

,LATITUDE,LONGITUDE,SIC Code,Year Found,Employees (Single Site),Employees (Domestic Ultimate Total),Employees (Global Ultimate Total),Sales (Domestic Ultimate Total USD),Is Domestic Ultimate,Is Global Ultimate,Import/Export Status_Missing
1,1.291294,103.827476,277,2015.0,39.0,100.0,100.0,7.093536e+09,False,False,True
2,1.300144,103.857517,459,1993.0,4.0,4.0,4.0,1.026308e+06,True,False,True
3,1.300785,103.791263,459,2006.0,10.0,100.0,100.0,7.339898e+10,False,False,True
5,1.444773,103.812740,308,1986.0,300.0,4.0,4.0,1.026308e+06,False,False,True
7,1.282887,103.850849,459,2010.0,10.0,4.0,4.0,1.026308e+06,False,False,True

Modelling

In [ ]:
from sklearn.model_selection import train_test_split, cross_val_score, KFold
from sklearn.metrics import accuracy_score, mean_squared_error, r2_score
import xgboost as xgb
from sklearn.preprocessing import StandardScaler
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.ensemble import GradientBoostingRegressor

In [ ]:
df4.head()

,LATITUDE,LONGITUDE,SIC Code,Year Found,Employees (Single Site),Employees (Domestic Ultimate Total),Employees (Global Ultimate Total),Sales (Domestic Ultimate Total USD),Is Domestic Ultimate,Is Global Ultimate,Import/Export Status_Missing
1,1.291294,103.827476,277,2015.0,39.0,100.0,100.0,7.093536e+09,False,False,True
2,1.300144,103.857517,459,1993.0,4.0,4.0,4.0,1.026308e+06,True,False,True
3,1.300785,103.791263,459,2006.0,10.0,100.0,100.0,7.339898e+10,False,False,True
5,1.444773,103.812740,308,1986.0,300.0,4.0,4.0,1.026308e+06,False,False,True
7,1.282887,103.850849,459,2010.0,10.0,4.0,4.0,1.026308e+06,False,False,True

In [ ]:
X = df4.drop('Sales (Domestic Ultimate Total USD)', axis=1)
y = df4['Sales (Domestic Ultimate Total USD)']


df4.info()
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize the GradientBoostingRegressor
model = GradientBoostingRegressor(random_state=42)

# Use k-fold cross-validation with 10 folds
model_10 = GradientBoostingRegressor(random_state=42)
kf = KFold(n_splits=10, shuffle=True, random_state=42)



# Perform cross-validation and get R-squared scores
cv_scores = cross_val_score(model, X_train, y_train, cv=kf, scoring='r2')

# Print the R-squared scores for each fold
print("Cross-Validation R-squared scores:", cv_scores)

# Print the mean and standard deviation of the R-squared scores
print("Mean R-squared score:", cv_scores.mean())
print("Standard Deviation of R-squared scores:", cv_scores.std())

# Train the model on the entire training set
model_10.fit(X_train, y_train)

# Evaluate the model on the test set
test_score = model_10.score(X_test, y_test)
print("Test R-squared score:", test_score)

<class 'pandas.core.frame.DataFrame'>
Index: 14311 entries, 1 to 29181
Data columns (total 11 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   LATITUDE                             14311 non-null  float64
 1   LONGITUDE                            14311 non-null  float64
 2   SIC Code                             14311 non-null  int64
 3   Year Found                           14311 non-null  float64
 4   Employees (Single Site)              14311 non-null  float64
 5   Employees (Domestic Ultimate Total)  14311 non-null  float64
 6   Employees (Global Ultimate Total)    14311 non-null  float64
 7   Sales (Domestic Ultimate Total USD)  14311 non-null  float64
 8   Is Domestic Ultimate                 14311 non-null  bool
 9   Is Global Ultimate                   14311 non-null  bool
 10  Import/Export Status_Missing         14311 non-null  bool
dtypes: bool(3), float64(7), int64(1)
memory usage: 1.0 MB

Cross-Validation R-squared scores: [-0.01362977  0.33598502 -0.83694518 -0.28125395  0.0187886  -0.0731715
  0.48520144  0.59061308  0.29645289  0.12470294]
Mean R-squared score: 0.06467435662781627
Standard Deviation of R-squared scores: 0.3929645631581431
Test R-squared score: 0.24815312139766432

## The cell below is **NOT** to be removed
##### The function is to be amended so that it accepts the given input (dataframe) and returns the required output (list). 
##### It is recommended to test the function out prior to submission
-------------------------------------------------------------------------------------------------------------------------------
##### The hidden_data parsed into the function below will have the same layout columns wise as the dataset *SENT* to you
##### Thus, ensure that steps taken to modify the initial dataset to fit into the model are also carried out in the function below

In [ ]:
def testing_hidden_data(hidden_data: pd.DataFrame) -> list:
    '''DO NOT REMOVE THIS FUNCTION.

The function accepts a dataframe as input and return an iterable (list)
of binary classes as output.

The function should be coded to test on hidden data
and should include any preprocessing functions needed for your model to perform. 
    
All relevant code MUST be included in this function.'''

    result = [] 
    return result

##### Cell to check testing_hidden_data function

In [ ]:
# This cell should output a list of predictions.
test_df = pd.read_csv(filepath)
test_df = test_df.drop(columns=['Sales (Domestic Ultimate Total USD)'])
print(testing_hidden_data(test_df))

[]

### Please have the filename renamed and ensure that it can be run with the requirements above being met. All the best!